import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

/**
 * Static Exportsにおいて利用できない機能を`next dev`のときにエラーにする設定。
 *
 * @see https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#dynamic
 */
export const dynamic = 'error';

/**
 * Metadataは`layout.tsx`か`page.tsx`で定義できる。
 *
 * Metadataには静的な`metadata`オブジェクトをexportする方法と、
 * 動的な`generateMetadata`関数をexportする方法がある。
 * どちらもServer Componentsでのみ利用可能。
 *
 * @see https://nextjs.org/docs/app/building-your-application/optimizing/metadata
 */
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="">
          <nav className="h-20 flex justify-center items-center gap-4">
            <Link href="/" className="text-lg hover:underline">
              Home
            </Link>
            <Link href="/foo" className="text-lg hover:underline">
              Foo
            </Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
